/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.glass.events.KeyEvent;
import java.awt.List;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import static vista.Pedido.obtenerFecha;

/**
 *
 * @author Roque
 */
public class Compra extends javax.swing.JPanel {

    public DefaultTableModel modelo_compra = new DefaultTableModel();

    public Compra() {
        initComponents();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        modelo_compra.addColumn("Descripción");
        modelo_compra.addColumn("Costo");

        tabla_compra.setModel(modelo_compra);

        //   tabla_compra.getColumnModel().getColumn(0).setPreferredWidth(150);
        tabla_compra.getColumnModel().getColumn(0).setMaxWidth(170);
        tabla_compra.getColumnModel().getColumn(0).setMinWidth(170);
        tabla_compra.getColumnModel().getColumn(1).setMaxWidth(130);
        tabla_compra.getColumnModel().getColumn(1).setMinWidth(130);
        tabla_compra.getColumnModel().getColumn(1).setResizable(false);

        //Manejo de Fecha
        lb_fecha.setText(obtenerFecha());
        lb_fechaAlreves.setText(devolverFecha());
        tf_fechaAlreves.setText(devolverFecha());
        tf_fechaAlreves.setVisible(false);
        lb_fechaAlreves.setVisible(false);

    }

    public void insertarDatosCompras() {

        String[] datos = new String[2];

        int precio = Integer.parseInt(tf_pago.getText());

        if (tf_desc.getText().equals("")) {
            datos[0] = "---";

        } else {

         datos[0] = tf_desc.getText();
        }
        datos[1] = String.valueOf(precio);
        modelo_compra.addRow(datos);

        tabla_compra.setModel(modelo_compra);

    }

    public void obtenerTotal() {

        int total = 0;

        for (int i = 0; i < tabla_compra.getRowCount(); i++) {

            total = total + Integer.parseInt(tabla_compra.getValueAt(i, 1).toString());

        }

        lb_total.setText(String.valueOf("$ " + total));

    }

    public static String obtenerFecha() {
        Date fecha = new Date();
        SimpleDateFormat formato_fecha = new SimpleDateFormat("dd/MM/YYYY");

        return formato_fecha.format(fecha);
    }

    public static String devolverFecha() {
        Date fecha_actual = new Date();
        SimpleDateFormat formato_fecha_actual = new SimpleDateFormat("YYYY-MM-dd");

        return formato_fecha_actual.format(fecha_actual);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_desc = new javax.swing.JTextField();
        tf_pago = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_compra = new javax.swing.JTable();
        lb_total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        lb_fechaAlreves = new javax.swing.JLabel();
        tf_fechaAlreves = new javax.swing.JTextField();
        btn_ag = new keeptoo.KButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_g = new keeptoo.KButton();
        btn_e = new keeptoo.KButton();
        kButton1 = new keeptoo.KButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 138, 139));
        jLabel1.setText("Ingrese los productos comprados");

        tf_desc.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tf_desc.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf_pago.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tf_pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_pagoKeyPressed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tabla_compra.setBackground(new java.awt.Color(247, 247, 247));
        tabla_compra.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        tabla_compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_compra.setGridColor(new java.awt.Color(247, 247, 247));
        tabla_compra.setRowHeight(20);
        tabla_compra.setSelectionBackground(new java.awt.Color(251, 212, 109));
        jScrollPane2.setViewportView(tabla_compra);

        lb_total.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 138, 139));
        jLabel2.setText("Total: ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_fecha.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lb_fecha.setForeground(new java.awt.Color(7, 3, 26));

        btn_ag.setText("Agregar");
        btn_ag.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_ag.setkBackGroundColor(new java.awt.Color(79, 138, 139));
        btn_ag.setkBorderRadius(18);
        btn_ag.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_ag.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        btn_ag.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        btn_ag.setkHoverStartColor(new java.awt.Color(79, 138, 139));
        btn_ag.setkStartColor(new java.awt.Color(79, 138, 139));
        btn_ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Descripción");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Costo");

        btn_g.setText("Guardar");
        btn_g.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_g.setkBackGroundColor(new java.awt.Color(79, 138, 139));
        btn_g.setkBorderRadius(18);
        btn_g.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_g.setkHoverEndColor(new java.awt.Color(79, 138, 139));
        btn_g.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        btn_g.setkHoverStartColor(new java.awt.Color(79, 138, 139));
        btn_g.setkStartColor(new java.awt.Color(79, 138, 139));

        btn_e.setText("Eliminar");
        btn_e.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_e.setkBackGroundColor(new java.awt.Color(79, 138, 139));
        btn_e.setkBorderRadius(18);
        btn_e.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_e.setkHoverEndColor(new java.awt.Color(79, 138, 139));
        btn_e.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        btn_e.setkHoverStartColor(new java.awt.Color(79, 138, 139));
        btn_e.setkStartColor(new java.awt.Color(79, 138, 139));
        btn_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eActionPerformed(evt);
            }
        });

        kButton1.setText("Ver informe");
        kButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kButton1.setkEndColor(new java.awt.Color(79, 138, 139));
        kButton1.setkHoverEndColor(new java.awt.Color(79, 138, 139));
        kButton1.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        kButton1.setkHoverStartColor(new java.awt.Color(79, 138, 139));
        kButton1.setkSelectedColor(new java.awt.Color(79, 138, 139));
        kButton1.setkStartColor(new java.awt.Color(79, 138, 139));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300)
                        .addComponent(lb_fechaAlreves, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(585, 585, 585)
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tf_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(tf_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_ag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_g, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_e, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(102, 102, 102)
                            .addComponent(tf_fechaAlreves, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lb_fechaAlreves, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(tf_fechaAlreves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_ag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btn_g, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_e, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_pagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pagoKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {
                insertarDatosCompras();
                tf_desc.setText("");
                tf_pago.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Por favor complete los datos de forma correcta");
            }

            obtenerTotal();

        }

    }//GEN-LAST:event_tf_pagoKeyPressed

    private void btn_agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agActionPerformed

        try {
            insertarDatosCompras();
            this.tf_desc.setText("");
            this.tf_pago.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor complete los datos de forma correcta");
        }

        obtenerTotal();


    }//GEN-LAST:event_btn_agActionPerformed

    private void btn_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eActionPerformed

        int fila = tabla_compra.getSelectedRow();

        if (fila >= 0) {

            modelo_compra.removeRow(fila);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione registro a eliminar");
        }

    }//GEN-LAST:event_btn_eActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
       
        
       Gasto gasto = new Gasto();
       
       gasto.setLocationRelativeTo(null);
       
       gasto.setVisible(true);
       
       gasto.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        
        
        
    }//GEN-LAST:event_kButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public keeptoo.KButton btn_ag;
    public keeptoo.KButton btn_e;
    public keeptoo.KButton btn_g;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KButton kButton1;
    public javax.swing.JLabel lb_fecha;
    public javax.swing.JLabel lb_fechaAlreves;
    public javax.swing.JLabel lb_total;
    public javax.swing.JTable tabla_compra;
    public javax.swing.JTextField tf_desc;
    public javax.swing.JTextField tf_fechaAlreves;
    public javax.swing.JTextField tf_pago;
    // End of variables declaration//GEN-END:variables
}
