/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ItemEvent;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import modelo.Comida;

/**
 *
 * @author Roque
 */
public class PanelAgregar extends javax.swing.JPanel {

    /**
     * Creates new form PanelAgregar
     *
     */
    Comida comida = new Comida();

    public PanelAgregar() {
        initComponents();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        lb_idMenu.setVisible(false);

        
      

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<String>(comida.mostrarComidas());

        cb_agregarS.setModel(modelo);

        tf_respaldo.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_agregarS = new javax.swing.JComboBox<>();
        tf_agregar = new javax.swing.JTextField();
        sepAgregar = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lb_idMenu = new javax.swing.JLabel();
        tf_precioA = new javax.swing.JTextField();
        sepAgregar1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_addS = new javax.swing.JButton();
        tf_respaldo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(530, 158));

        cb_agregarS.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cb_agregarS.setMaximumRowCount(30);
        cb_agregarS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        cb_agregarS.setToolTipText("");
        cb_agregarS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_agregarSItemStateChanged(evt);
            }
        });

        tf_agregar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        tf_agregar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_agregar.setBorder(null);
        tf_agregar.setMinimumSize(new java.awt.Dimension(6, 23));
        tf_agregar.setName(""); // NOI18N

        sepAgregar.setForeground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        jLabel2.setText("Nombre nuevo tipo");

        lb_idMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tf_precioA.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        tf_precioA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_precioA.setBorder(null);

        sepAgregar1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        jLabel3.setText("Precio");

        jLabel4.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        jLabel4.setText("Seleccione la sección");

        btn_addS.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btn_addS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btn_addS.setText("Agregar Seccion");
        btn_addS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addS.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_addS.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cb_agregarS, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_addS))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tf_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_precioA, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(tf_respaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(sepAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lb_idMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(cb_agregarS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btn_addS)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2))
                    .addComponent(tf_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sepAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tf_precioA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_respaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(sepAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lb_idMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_agregarSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_agregarSItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            if (cb_agregarS.getSelectedIndex() > 0) {

                tf_agregar.setVisible(true);
                sepAgregar.setVisible(true);
                jLabel2.setVisible(true);

            }

        }

    }//GEN-LAST:event_cb_agregarSItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_addS;
    public javax.swing.JComboBox<String> cb_agregarS;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel lb_idMenu;
    private javax.swing.JSeparator sepAgregar;
    private javax.swing.JSeparator sepAgregar1;
    public javax.swing.JTextField tf_agregar;
    public javax.swing.JTextField tf_precioA;
    public javax.swing.JTextField tf_respaldo;
    // End of variables declaration//GEN-END:variables
}
